/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ysag_dirac_MainActivity */

#ifndef _Included_com_ysag_dirac_MainActivity
#define _Included_com_ysag_dirac_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ysag_dirac_MainActivity
 * Method:    process
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ysag_dirac_MainActivity_process
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
