/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ysag_dirac_MainActivity_BlurType */

#ifndef _Included_com_ysag_dirac_MainActivity_BlurType
#define _Included_com_ysag_dirac_MainActivity_BlurType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
